### ISSUE TITLE
#PickhardtPayments: Make use of minimum known liquidity

### ISSUE THREAD

**Issue by C-Otto** [C-Otto/lnd-manageJ#10]
Make use of minimum known liquidity (if >0). When splitting the channel into 5 pieces, first add a 0-cost (100% probability) segment with the amount that is known, then add 4 segments with increasing costs. See @RenePickhardt's code for details.

**Comment by renepickhardt** [comment]
The reason for doing 1 zero cost edge and divide the residual amount into 4 pieces is that in this way I control the number of edges for the the optimization problem. You will see that the runtime of the solver increases directly if you do the piece wise linearization more quickly. 
Of course this might lead to some absurd situations. Imagine we know a channel has only 1 satoshi of liquidity with this method we effectively split that channel into 1 piece for the 1 sat and then 4 pieces that are roughly 25% of the channel capacity. That being said the entire approach is an approximation afterall anyway.

**Comment by C-Otto** [comment]
So the main motivation is to keep the runtime unaffected, i.e. having 6 instead of 5 edges for a possibly large number of channels would make things too slow?

I only include the 0-cost edges if the minimum liquidity is at least as much as the quantization amount, but I guess the problem still holds. A rather small minimum liquidity could lead to a rather small first edges, with a large percentage of the remaining capacity split into 4 or 5 chunks.
