### ISSUE TITLE
Feature Request: List pending channels

### ISSUE THREAD

**Issue by danielbroll** [C-Otto/lnd-manageJ#83]
**Is your feature request related to a problem? Please describe.**
Fees are high, jpgs are clogging up the chain, channel might take a while until they confirm.

**Describe the solution you'd like**
Showing pending channels would help to stay on top!
![image](https://github.com/C-Otto/lnd-manageJ/assets/98091744/eda23b0a-34ff-4627-b048-12b061c8ccab)

**Additional context**
- [draft branch](https://github.com/danielbroll/lnd-manageJ/commits/pending-channels) 
- [open question on how to model the channel inheritance hierarchy](https://github.com/danielbroll/lnd-manageJ/commit/9cd376d03964820c33b6775d165efebd890f7bff#r112745384)

**Comment by C-Otto** [comment]
It's tricky, see my comment in your code. What kind of information do you expect to see? For me, lnd-manageJ mostly helps gather information that is tricky to acquire, for example routing statistics or details about on-chain fee costs. For pending channels there's not a whole lot to see, especially if you already know how to run `lncli pendingchannels` (which, I admit, isn't a GUI).

**Comment by danielbroll** [comment]
Thanks for taking a look at the branch.

I would like to see:
- the channel initiator & capacity
- the alias (not part of `lncli pendingchannels`)
- the lnd-manageJ UI link to the node
- a direct link to [ambos.space](https://www.amboss.space/) to investigate who opened a channel to my node.

Would you rather not have those information in the UI to keep the code base lean?

I personally use the UI to get an overview of my node and to see if there is something to do and then use `lnci` and scripts for the actual execution.

I guess having the feature richness of [thunderhub](https://www.thunderhub.io/) is not the goal for the project? 
Where to draw the line?

**Comment by C-Otto** [comment]
The project doesn't really have a goal, I must admit. Personally I don't see the advantage, as I'm quite happy with my current toolset (mostly `lncli`), and I don't need support from lnd-manageJ for that. On the other hand, I don't use the UI at all, so I'm not really part of the target demographic here. Feel free to implement this, but please don't fiddle to much with the existing code regarding "real" as in non-pending channels.

**Comment by C-Otto** [comment]
Oh, one more thing. You're only talking about not-yet-opened channels, but if you also consider not-yet-closed channels, this is more interesting. Especially with the recent chaos, getting some answers to questions like the following would help. I'm not too happy with my (bash-script based) toolchain, so integrating this into lnd-manageJ might help.

* Who initiated the close (and who has to pay for it)?
* How much did I already pay (including confirmed, possibly also unconfirmed, sweep transactions)
* Why did a force-close happen?
* How much liquidity is locked, and for how long?
* Which channels are stuck (coop close without close transactions)?
* Which close transactions are waiting for confirmation (how long, at which fee rate)?

**Comment by C-Otto** [comment]
Fixed by #84
